<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Click to see Screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Fri_Aug_16_09_23_49_IDT_2019.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Fri_Aug_16_09_23_49_IDT_2019.jpg><img src=Fri_Aug_16_09_23_49_IDT_2019.jpg height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[Click to see Screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Fri_Aug_16_09_23_51_IDT_2019.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Fri_Aug_16_09_23_51_IDT_2019.jpg><img src=Fri_Aug_16_09_23_51_IDT_2019.jpg height=200 width=200></img></a>]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="2324" started-at="2019-08-16T06:23:48Z" finished-at="2019-08-16T06:23:51Z">
    <groups>
    </groups>
    <test name="Bank Manager Login Test" duration-ms="1287" started-at="2019-08-16T06:23:48Z" finished-at="2019-08-16T06:23:49Z">
      <class name="com.w2a.testcases.BankManagerLoginTest">
        <test-method status="FAIL" signature="loginAsBankManager()[pri:0, instance:com.w2a.testcases.BankManagerLoginTest@f381794]" name="loginAsBankManager" duration-ms="927" started-at="2019-08-16T06:23:48Z" finished-at="2019-08-16T06:23:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login not Successfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login not Successfully
at org.testng.Assert.fail(Assert.java:96)
at com.w2a.testcases.BankManagerLoginTest.loginAsBankManager(BankManagerLoginTest.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see Screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Fri_Aug_16_09_23_49_IDT_2019.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Fri_Aug_16_09_23_49_IDT_2019.jpg><img src=Fri_Aug_16_09_23_49_IDT_2019.jpg height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- com.w2a.testcases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test name="Add Customer Test" duration-ms="1024" started-at="2019-08-16T06:23:50Z" finished-at="2019-08-16T06:23:51Z">
      <class name="com.w2a.testcases.AddCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.w2a.testcases.AddCustomerTest@7690781]" name="setUp" is-config="true" duration-ms="7217" started-at="2019-08-16T06:23:41Z" finished-at="2019-08-16T06:23:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="AddCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.w2a.testcases.AddCustomerTest@7690781]" name="AddCustomer" duration-ms="653" started-at="2019-08-16T06:23:50Z" data-provider="getData" finished-at="2019-08-16T06:23:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[omer]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[kenig]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[abc123]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Customer not added Successfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Customer not added Successfully
at org.testng.Assert.fail(Assert.java:96)
at com.w2a.testcases.AddCustomerTest.AddCustomer(AddCustomerTest.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see Screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Fri_Aug_16_09_23_51_IDT_2019.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Fri_Aug_16_09_23_51_IDT_2019.jpg><img src=Fri_Aug_16_09_23_51_IDT_2019.jpg height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- AddCustomer -->
        <test-method status="PASS" signature="tearDwon()[pri:0, instance:com.w2a.testcases.AddCustomerTest@7690781]" name="tearDwon" is-config="true" duration-ms="778" started-at="2019-08-16T06:23:51Z" finished-at="2019-08-16T06:23:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDwon -->
      </class> <!-- com.w2a.testcases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
  </suite> <!-- Suite -->
</testng-results>
